
package fr.fortytwo.spring.service.config;

import org.junit.jupiter.api.BeforeEach;

import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import com.zaxxer.hikari.HikariDataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.Assert.assertNotNull;
import org.springframework.beans.factory.annotation.Qualifier;
import java.sql.Connection;
import java.sql.SQLException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;

import fr.fortytwo.spring.service.config.ApplicationConfig;
import fr.fortytwo.spring.service.services.UsersService;
import org.springframework.context.annotation.Primary;

@Configuration
@ComponentScan(basePackages = "fr.fortytwo.spring.service")
public class TestApplicationConfig {
    private EmbeddedDatabase ds;
    private JdbcTemplate jdbcTemplate;

    @Bean(name = "embeddedDatabaseDataSource")
    public DataSource getDataSource() {
        EmbeddedDatabase ds = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.HSQL)
                .build();
        this.jdbcTemplate = new JdbcTemplate(ds);
        /// first reset the database
        this.jdbcTemplate.execute("DROP TABLE IF EXISTS users");
        jdbcTemplate.execute(
                "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,email VARCHAR(255))");
        return ds;
    }
}
